services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "7878:7878"
    volumes:
      - radarr_config:/config
      - ${MEDIA_LOCAL_PATH:-/Users/bill/Documents/media_local}:/media_local
      - ${MEDIA_EXTERNAL_PATH:-/Volumes/Stuff/media}:/media_external

volumes:
  radarr_config:
