services:
  portainer:
    extends:
      file: ./services/portainer.yml
      service: portainer

  sonarr:
    extends:
      file: ./services/sonarr.yml
      service: sonarr

  radarr:
    extends:
      file: ./services/radarr.yml
      service: radarr

  jellyfin:
    extends:
      file: ./services/jellyfin.yml
      service: jellyfin

  audiobookshelf:
    extends:
      file: ./services/audiobookshelf.yml
      service: audiobookshelf

  homarr:
    extends:
      file: ./services/homarr.yml
      service: homarr

  uptime-kuma:
    extends:
      file: ./services/uptime-kuma.yml
      service: uptime-kuma

  metabase:
    extends:
      file: ./services/metabase.yml
      service: metabase

  monica-db:
    extends:
      file: ./services/monica-db.yml
      service: monica-db

  monica:
    extends:
      file: ./services/monica.yml
      service: monica
    depends_on:
      - monica-db

  vaultwarden:
    extends:
      file: ./services/vaultwarden.yml
      service: vaultwarden

volumes:
  portainer_data:
  metabase_data:
  monica_data:
  monica_db_data:
  vaultwarden_data:

networks:
  media-stack:
    driver: bridge
