services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "3001:3001"
    volumes:
      - ../config/uptime-kuma:/app/data
    networks:
      - media-stack

networks:
  media-stack:
    driver: bridge
