services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - ${CONFIG_ROOT:-/Users/bill/Documents/GitHub/docker-composes/data}/jellyfin/config:/config
      - ${CONFIG_ROOT:-/Users/bill/Documents/GitHub/docker-composes/data}/jellyfin/cache:/cache
      - ${MEDIA_LOCAL_PATH:-/Users/bill/Documents/media_local}:/media_local
      - ${MEDIA_EXTERNAL_PATH:-/Volumes/Stuff/media}:/media_external
